### ISSUE TITLE
Exception when adding a bot

### ISSUE THREAD

**Issue by WrayOfSunshine** [Chronoes/auto-xdcc#46]
I'm trying to work out how to use this, so this could be user error, but when I do /axdcc bot add (botname) I get this error:

```
> Exception ignored from cffi callback <function _on_command_hook at 0x7f7d41259870>:
>  Traceback (most recent call last):
>    File "<init code for '_hexchat_embedded'>", line 245, in _on_command_hook
>    File "/home/user/.config/hexchat/addons/auto_xdcc.py", line 232, in axdcc_main_cb
>      return_code = args.handler(args)
>    File "/home/user/.config/hexchat/addons/auto_xdcc/argparse.py", line 256, in addbot_handler
>      bots = set(config['trusted'])
>    File "/usr/lib/python3.10/collections/__init__.py", line 1106, in __getitem__
>      raise KeyError(key)
>  KeyError: 'trusted'
>  Exception ignored in sys.unraisablehook: <built-in function unraisablehook>
>  AttributeError: 'Stdout' object has no attribute 'flush'
> * axdcc :Unknown command
```

Any idea what could cause this?

**Comment by oosran** [comment]
This looks like an artifact from before 'trusted' was moved from being a global config key to a key belonging to a packlist, so the bot subcommands are probably all no longer functioning, and it hasn't be discovered in the past 6 years because there has been no need to use those commands given the defaults I suppose. I don't think this'll be solved anytime soon, but good to know.
For the time being, the easiest way to work around the issue would be to manually modify the config json to add any trusted bots to whichever packlist you want to add to/modify.
